container:
  image: rust:latest

test_task:
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  build_script:
    - rustup component add clippy
    - cargo build
  test_script: cargo run -- verify
  before_cache_script: rm -rf $CARGO_HOME/registry/index
