on: push

name: Rust

jobs:
  verify_solutions:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo run -- verify
